apiVersion: v1
kind: Service
metadata:
  name: project
  labels:
    app: project
spec:
  type: ClusterIP
  selector:
    app: project
  ports:
    - port: 2344
      protocol: TCP
      targetPort: 3001