apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-pv
          persistentVolumeClaim:
            claimName: shared-claim
      containers:
        - name: log-output-reader
          image: log-output-reader:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: shared-pv
            mountPath: /usr/src/app/files
        - name: log-output-writer
          image: log-output-writer:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: shared-pv
            mountPath: /usr/src/app/files