apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-output-claim
  namespace: course
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi