apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
      - name: shared-pv
        persistentVolumeClaim:
          claimName: shared-claim
      containers:
        - name: ping-pong
          image: ping-pong:latest
          volumeMounts:
            - name: shared-pv
              mountPath: /usr/src/app/files
          imagePullPolicy: IfNotPresent