apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap.yaml
  - manifests/ingress.yaml
  - manifests/persistentvolume.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/statefulset.yaml
  - todo-app/manifests/deployment.yaml
  - todo-app/manifests/service.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/service.yaml
images:
  - name: BACKEND/IMAGE
  - name: APP/IMAGE