apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: course
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
      - name: log-output-configmap
        configMap:
          name: log-output-configmap
      containers:
        - name: ping-pong
          image: ping-pong:latest
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: MESSAGE
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: USER
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: DB
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: DB_PORT
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: log-output-configmap
              mountPath: /usr/src/app/config
          imagePullPolicy: IfNotPresent