apiVersion: v1
kind: Service
metadata:
  name: ping-pong
  labels:
    app: ping-pong
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - port: 2344
      protocol: TCP
      targetPort: 3003