apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
      - name: todo-app-pv
        persistentVolumeClaim:
          claimName: todo-app-claim
      containers:
        - name: todo-app
          image: APP/IMAGE
          volumeMounts:
            - name: todo-app-pv
              mountPath: /usr/src/app/files
          imagePullPolicy: IfNotPresent