apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 2344
      protocol: TCP
      targetPort: 3001