apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ea3w3WHiiv+vSkgRoYYM4UnE+xfrltDHNNEkClq0FfIKDdu8kIb/IJghiJwkyrOWllzEBh4vl1SXRe+pn/zc1tvOI80mKNZzwiM=,iv:QcDjBFHLIEy0EhMIFPgiZngAHWixGNoCJovfnxb+9F4=,tag:31ocFNH3ILyAaBx5l0AjpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ap77hvmz3x9h53phlnzma56xm9py6kd2cypfy4qazehx9s0dzy7salgz3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVM2xXVjd0amxNRDZvKy9C
            M01vMVhRZ2hQbHpqWDZ6bTA0NUppOEE4ZFNrCjJHaEFCSGlUOG1KVExCQThlWUl6
            RzgvMEEyZ0o0VmtJd09OUG1SUXk1ZDQKLS0tIHB4RGRidFRaSTc1VzJEYXF3bVlT
            TWJtNVdLMlk2eS83dUd2aXJIT0ZJanMKD0aIDLDA3wZzJSpQliwlNwnaqWOIScLb
            RLkK4orj2Fj6AWPSE06FafbgIuLxvG1sMajtr/pueHubiAtFW76/xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T11:20:26Z"
    mac: ENC[AES256_GCM,data:RI9B9jpZ8Fv6rbpITl67rz38EzBXT5nXah85drC++aWy/Vrc4tiAN+CcV818SkBkmip5Wtopr0YCJ+kY3ZQNDkmCkLu6twP9F0TlhpniUck1vZbWylE+LaZyJQszKk9i53bgjHzLZFgR957Qh0et2Rk1scDWLo/IwN3bd/ZpvYo=,iv:z0lqV2j71hN2Ks+7w7UI/Tz2+zD7UOXcnsdb76Hm4j8=,tag:+0agNQ94dZsg/YwZn5dALw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
