apiVersion: v1
kind: Service
metadata:
  namespace: course
  name: ping-pong-svc
  labels:
    app: ping-pong
spec:
  type: LoadBalancer
  selector:
    app: ping-pong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001