apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: course
  name: log-output-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi