apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-app
  labels:
    app: todo-app
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 2344
      protocol: TCP
      targetPort: 3001